hw/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from instructors.views import hello, hello_python, sum_two, http, instructors_list
from Courses.views import course
from django.urls import include
from students.views import students_list, student


def results(request, a, b, c):
    list=[]
    list.append(a)
    list.append(b)
    list.append(c)
    print(list)

    for i in list:
        print(i)
    return HttpResponse(list)


urlpatterns = [
    path('', hello, name='home'),
    path('hello_python/', hello_python, name='hello_python' ),
    path('http/', http, name='http' ),
    re_path('sum/(?P<a>\d+)/(?P<b>\d+)/', sum_two, name='sum'),
    path('admin/', admin.site.urls),
    path('instructors_list/', instructors_list, name='instructors_list'),
    path('course/<int:id>/', course, name='course_url'),
    # path('results/(\d+)/', include('quadratic.urls')),
    re_path('results/a=(?P<a>\w+)&b=(?P<b>\w+)&c=(?P<c>\w+)/', results),
    path('students/', students_list, name='students_list'),
    path('student/<int:id>/', student, name='student'),
]

quadratic/urls.py
from django.urls import path, re_path
from django.shortcuts import render
from .views import quadratic_results


urlpatterns = [
    path('',  quadratic_results),

]

Courses/models.py
from django.db import models

class Course(models.Model):
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=100)
    description = models.TextField(max_length=300)

    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = "Курс"
        verbose_name_plural = "Курсы"



class Lesson(models.Model):
    """docstring for Lesson."""
    subject = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE, blank=True)
    order = models.PositiveIntegerField(blank=True)

    def __str__(self):
        return '%s' % (self.subject)

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


# from Courses.models import Course, Lesson
#
#         a = Course.objects.create(name='python course', short_description='Программирование на языке Python. Уровень 2. Продвинутый курс', description='Вы занимаетесь программированием и хотите повысить свою квалификацию или систематизировать имеющиеся знания и навыки? Хотите изучить перспективный язык программирования Python? Вы - системный администратор или IT-специалист и у Вас возникла необходимость в освоении данного языка программирования?')

# a = Lesson.objects.create(subject='Тема 1', description='Вводное занятие', course=python course)
# a = Lesson.objects.create(subject='Тема 2', description='MVC архитектура')

coaches/models.py
from django.db import models

class Coach(model.Models):
    user = models.OneToOneField(User)
    date_of_birth = models.DateField()
    M = 'Male'
    F = 'Female'
    GENDER_CHOICES = (
        (M, 'Male'),
        (F, 'Female'),
    )
    gender = models.Charfield(choices=GENDER_CHOICES, default=None)
    phone = models.CharField(max_length=20)
    adress = models.CharField(max_length=50)
    skype = models.CharField(max_length=25)
    discription = models.TextField(max_length=250)

    def __str__(self):
        return self.name

instructors/models.py
from django.db import models
from django.conf import settings
from Courses.models import Course

class Position(models.Model):
    name = models.CharField(max_length=50, help_text="This is name")
    def __str__(self):
        return '%s' % (self.name)
    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'



class Instructor(models.Model):
    name = models.CharField( verbose_name='Instructor Name', max_length=50, help_text="This is name")
    surname = models.CharField(max_length=50)
    course = models.ManyToManyField(Course)
    date_of_birth = models.DateField(null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)

    phone = models.CharField(max_length=15, null=True, blank=True)
    slug = models.SlugField(unique=True)
    is_active = models.BooleanField(default=True)
    gender = models.CharField(max_length=1, choices=[('m', 'Male'), ('f', 'Female'),])

    position = models.ForeignKey(Position, null=True, blank=True, on_delete='CASCADE')

    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete='CASCADE')

    def __str__(self):
        return '%s %s' % (self.name, self.surname)

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'

quadratic/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models
from Courses.models import Course


class Student(models.Model):
    name = models.CharField(max_length=25)
    surname = models.CharField(max_length=25)
    date_of_birth = models.DateField()
    email = models.EmailField(help_text='A valid email address, please.')
    phone = models.CharField(max_length=25)
    addres = models.CharField(max_length=50)
    skype = models.CharField(max_length=25)
    courses = models.ManyToManyField(Course)



    def __str__(self):
        return '%s' % (self.name)

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"

Courses/views.py
from django.shortcuts import render
from Courses.models import Course

def course(request, id):
    # course = Course.objects.filter(id = 'id')
    course = Course.objects.get(id__iexact=id)
    return render(request, 'course.html', context={'course':course})

coaches/views.py
from django.shortcuts import render

# Create your views here.

instructors/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from instructors.models import Instructor
from Courses.models import Course


def hello(request):
    courses = Course.objects.all()
    return render(request, "general.html", {"courses": courses})

def instructors_list(request):
    instructors = Instructor.objects.all()
    return render(request, "instructors_list.html", {"instructors": instructors})

def hello_python(request):
    return render(request, 'python.html' )

def http(request):
    response =  render(request, "http.html")
    return HttpResponseNotFound()

def sum_two(request, a, b):
    s = int(a) + int(b)
    return HttpResponse(s)

quadratic/views.py
from django.shortcuts import render


def quadratic_results(request):
    return render(request, 'quadratic/results.html')

students/views.py
from django.shortcuts import render
from students.models import Student
# from django.http import HttpResponse

def students_list(request):
    students = Student.objects.all()
    return render(request, 'students_list.html', {"students": students})

def student(request, id):
    student = Student.objects.get(id__iexact=id)
    return render(request, 'student.html', context={"student":student})

quadratic/templates/quadratic/results.html
Хэй-хэй

templates/Courses/course.html
{% extends "index.html" %}

{% block title %} {{ course.name }} {% endblock title %}

{% block content %}


<h1>{{ course.name }}</h1>
<p><font size="5">{{ course.description }}</font></p>
<hr>
<h2 class="">План курса</h2>

<table class="table-hover table-bordered">
    {% for lesson in course.lesson_set.all %}
        <tr align=left>
            <th>{{ lesson.subject }}</th>
            <th>{{ lesson.description }}</th>
        </tr>
    {% endfor %}
</table>

{% endblock %}

templates/general.html
{% extends "index.html" %}

{% block title %}>instructors list{% endblock title %}


{% block content %}

<h1>  Spaghetti code academy</h1>
<h6>  Научитесь создавать и программировать современные веб-интерфейсы, <br>
  использую много операторов GOTO (особенно переходов назад), исключений и <br>
  других конструкций, ухудшающих структурированность.</h6>
  <hr>
<h3>Выбирай на каком курсе хочешь учиться!</h3>


<br>


  <table class="table-hover table-bordered">

    {% for course in courses %}
    <tr>
      <th> <a href="{% url 'course_url' id=course.id %}"> {{course.name}} </a> </th>
      <th> {{course.short_description}} </th>
    </tr>
    {% endfor %}

  </table>


{% endblock %}

templates/http.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Главная страница</title>
  </head>
  <body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar w/ text</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">Кнопка</span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Главная <span class="sr-only">(текущая)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Свойства</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Ценообразование</a>
          </li>
        </ul>
        <span class="navbar-text">
          Текст навигационной панели со встроенными элементами
        </span>
      </div>
    </nav>
    <h1>HTTP</h1>

    <form method="post">
      <!-- {% csrf_token %} -->
      <input type="text" name="some"/>
      <input type="submit"/>
    </form>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block title %}Главная страница{% endblock title %}</title>
    <style>
        .template {
            margin-left: 20px; /* Убираем отступы */
        }
        th{
            padding: 5px 20px 5px 20px;
        }

    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">Кнопка</span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Главная <span class="sr-only">(текущая)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'students_list' %}" >Студенты</a>
          </li>
        </ul>
        <span class="navbar-text">
          Текст навигационной панели со встроенными элементами
        </span>
      </div>
    </nav>
<div class="template">

{% block content %}
{% endblock %}

</div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/instructors_list.html
{% extends "index.html" %}
{% block title %}>instructors list{% endblock title %}
{% block header %}Главная{% endblock header %}

{% block content %}

<h1>instructors list</h1>
{%for instructor in instructors%}
  <p>{{instructor.name}} {{instructor.surname}}</p>
{% endfor %}
{% endblock %}

templates/python.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">

<title>Инструктор Кекс</title>

<!-- Удалите строку ниже -->

<!-- <link rel="stylesheet" href="keks-style.css"> -->

</head>
  <body>
    <div class="container">

<header class="site-header">

<h1>Инструктор Кекс</h1>

<p>Обучение начинающих котят</p>
      </header>

      <section class="features">
        <h2>Почему я?</h2>
        <p>Я сам был котёнком, и вот я здесь</p>
        <p>Хозяин натренирован на 100%</p>
      </section>

      <section class="skills">
        <h2>Чему вы научитесь?</h2>
        <ul class="skills-list">
          <li>таскать еду из хозяйской тарелки</li>
          <li>придавать мебели винтажный стиль</li>
          <li>открывать дверь и не входить</li>
          <li>будить хозяина ночью</li>
        </ul>
      </section>

      <footer class="site-footer">
        <p>© Кекс, 2018</p>
        <p>Контактов нет, я сам вас найду</p>
      </footer>
    </div>
  </body>
</html>

templates/students/student.html
{% extends "index.html" %}

{% block title %}Студент{% endblock title %}

{% block content %}
<h1>Страница студента</h1>
<p><font size="5">{{ course.description }}</font></p>
<hr>

<table class="table-hover table-bordered">
        <tr>
            <th>фамилия имя</th>
            <th>{{ student.surname }} {{ student.name }}</th>
        </tr>

        <tr align=left>
            <th>дата рождения</th>
            <th>{{ student.date_of_birth }}</th>
        </tr>

        <tr align=left>
            <th>email</th>
            <th>{{ student.email }}</th>
        </tr>

        <tr align=left>
            <th>телефон</th>
            <th>{{ student.phone }}</th>
        </tr>

        <tr align=left>
            <th>адрес</th>
            <th>{{ student.addres }}</th>

        </tr>
        <tr align=left>
            <th>skype</th>
            <th>{{ student.skype }}</th>

        </tr>
        <tr align=left>
            <th>курсы</th>

            <th>
                {% for course in student.courses.all %}
                    <li><a href='{% url 'course_url' id=course.id %}'>{{ course.name }}</a></li>
                {% endfor %}
            </th>



        </tr>
</table>
{% endblock %}

templates/students/students_list.html
{% extends "index.html" %}

{% block title %}Студенты{% endblock title %}

{% block content %}
<h1>Список студентов</h1>
<p><font size="5">{{ course.description }}</font></p>
<hr>

<table class="table-hover table-bordered">
        <tr>
            <th>фамилия имя</th>
            <th>адрес</th>
            <th>skype</th>
            <th>курсы</th>
        </tr>
    {% for student in students %}
        <tr align=left>
            <th><a href="{% url 'student' id=student.id %}"> {{ student.surname }} {{ student.name }} </a></th>
            <th> {{ student.addres }} </th>
            <th> {{ student.skype }} </th>
            <th>
                {% for course in student.courses.all %}
                    <li><a href="{% url 'course_url' id=course.id %}"> {{ course.name }} </a></li>
                {% endfor %}
            </th>
        </tr>
    {% endfor %}
</table>
{% endblock %}